### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by sara990099** [datarhei/core-client-python#1]
Python 3.7.17
[GCC 9.4.0] on linux

`>from core_client import Client`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/core_client/__init__.py", line 227, in <module>
    submodule = importlib.import_module(submodule_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.7/dist-packages/core_client/base/api/v3_cluster_get_list.py", line 6, in <module>
    from ..models.v3 import ClusterNodeList
  File "/usr/local/lib/python3.7/dist-packages/core_client/base/models/v3/__init__.py", line 7, in <module>
    from .config_api_auth_auth0_tenant import ConfigApiAuthAuth0Tenant
  File "/usr/local/lib/python3.7/dist-packages/core_client/base/models/v3/config_api_auth_auth0_tenant.py", line 4, in <module>
    class ConfigApiAuthAuth0Tenant(BaseModel):
  File "/usr/local/lib/python3.7/dist-packages/core_client/base/models/v3/config_api_auth_auth0_tenant.py", line 19, in ConfigApiAuthAuth0Tenant
    users: list[str]
TypeError: 'type' object is not subscriptable

**Comment by jstabenow** [comment]
Python 3.11 or later is required.
